name: Docker Image CI (stable versions)

on:
  push:
    tags:
      - "v[0-9]*"
      - "!v*alpha*"
      - "!v*beta*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag version to be used for Docker image"
        required: true
        default: "latest"

jobs:
  build-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            usual2970/certimate
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=oci,dest=./certimate-image.tar

      - name: Display Docker images
        run: docker images

      - name: Save images
        run: docker save -o certimate-image-off.tar usual2970/certimate:main

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ./certimate-image-off.tar
          retention-days: 7
